# Generated by Django 3.2.8 on 2021-11-04 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CovidCertificate',
            fields=[
                ('national_id', models.CharField(default='', max_length=12, primary_key=True, serialize=False, unique=True)),
                ('fullname', models.CharField(max_length=500, null=True)),
                ('DoB', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('gender', models.CharField(max_length=10, null=True)),
                ('phone_number', models.CharField(max_length=12, null=True)),
                ('no_of_vaccination', models.SmallIntegerField()),
                ('vaccine_no1_type', models.CharField(max_length=100, null=True)),
                ('vaccination_no1_date', models.DateField(blank=True, null=True)),
                ('vaccine_no2_type', models.CharField(max_length=100, null=True)),
                ('vaccination_no2_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
