# Generated by Django 3.2.8 on 2021-11-04 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormalUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='authentication.user')),
                ('DoB', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('gender', models.CharField(max_length=1)),
                ('phone_number', models.CharField(max_length=12)),
                ('province', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('ward', models.CharField(max_length=50)),
                ('detailed_address', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalDeclaration',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='NormalUser.normaluser')),
                ('past_14d_travel', models.BooleanField(default=False)),
                ('departure_province', models.CharField(max_length=50)),
                ('departure_city', models.CharField(max_length=50)),
                ('departure_ward', models.CharField(max_length=50)),
                ('departure_detailed_place', models.CharField(max_length=500)),
                ('arrival_province', models.CharField(max_length=50)),
                ('arrival_city', models.CharField(max_length=50)),
                ('arrival_ward', models.CharField(max_length=50)),
                ('arrival_detailed_place', models.CharField(max_length=500)),
                ('past_14d_symptoms', models.BooleanField(default=False)),
                ('deltaild_description', models.CharField(max_length=5000)),
                ('in_contact_confirmed_COVID19_case', models.BooleanField(default=False)),
                ('in_contact_people_from_countries_with_COVID19', models.BooleanField(default=False)),
                ('in_contact_people_with_syptoms', models.BooleanField(default=False)),
            ],
        ),
    ]
