# Generated by Django 3.2.8 on 2021-11-11 04:47

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('NormalUser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicaldeclaration',
            name='declarationTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 11, 11, 46, 53, 215687)),
        ),
        migrations.AddField(
            model_name='medicaldeclaration',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicaldeclaration',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='NormalUser.normaluser'),
        ),
    ]
