# Generated by Django 3.2.8 on 2021-11-11 05:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('NormalUser', '0004_alter_medicaldeclaration_declarationtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicaldeclaration',
            name='declarationTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 11, 5, 1, 55, 159399, tzinfo=utc)),
        ),
    ]
