# Generated by Django 3.2.8 on 2021-11-11 05:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('NormalUser', '0007_alter_medicaldeclaration_declarationtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicaldeclaration',
            name='declarationTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
