# Generated by Django 3.2.8 on 2021-11-11 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NormalUser', '0008_alter_medicaldeclaration_declarationtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='medicaldeclaration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NormalUser.normaluser'),
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NormalUser.city')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NormalUser.province'),
        ),
        migrations.AlterField(
            model_name='medicaldeclaration',
            name='arrival_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arrival_city', to='NormalUser.city'),
        ),
        migrations.AlterField(
            model_name='medicaldeclaration',
            name='arrival_province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arrival_province', to='NormalUser.province'),
        ),
        migrations.AlterField(
            model_name='medicaldeclaration',
            name='arrival_ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arrival_ward', to='NormalUser.ward'),
        ),
        migrations.AlterField(
            model_name='medicaldeclaration',
            name='departure_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departure_city', to='NormalUser.city'),
        ),
        migrations.AlterField(
            model_name='medicaldeclaration',
            name='departure_province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departure_province', to='NormalUser.province'),
        ),
        migrations.AlterField(
            model_name='medicaldeclaration',
            name='departure_ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departure_ward', to='NormalUser.ward'),
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='NormalUser.city'),
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='NormalUser.province'),
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='NormalUser.ward'),
        ),
    ]
