# Generated by Django 3.2.8 on 2021-12-13 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NormalUser', '0014_alter_medicaldeclaration_arrival_detailed_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicaldeclaration',
            name='deltaild_description',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
